import './globals.css';
import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google';
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"

const bodyFont = Inter({
    subsets: ['latin'],
    weight: ['400'],
    display: 'swap',
});

const titleFont = Poppins({
    subsets: ['latin'],
    weight: ['600'],
    display: 'swap',
    variable: '--font-title',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${bodyFont.className} ${titleFont.variable} antialiased`}
            >
                {children}
                <SpeedInsights/>
                <Analytics/>
            </body>
        </html>
    );
}
